# See https://pre-commit.com for more information
ci:
  autofix_prs: false
  autoupdate_schedule: quarterly
  autoupdate_branch: pre-commit-autoupdate
  # Skip steps that won't run on pre-commit CI for various reasons,
  # mostly because they rely on local things.
  skip: [
    pixi-install,
  ]

# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.4.0'
    hooks:
      - id: check-added-large-files
        exclude: |
          (?x)(
            ^pixi.lock/|
            ^tests/regression/test_mean_preserving_interpolation/test_mean_preserving_interpolation_long_array_lai_kaplan_basic_.csv/|
            ^tests/regression/test_mean_preserving_interpolation/test_mean_preserving_interpolation_long_array_lai_kaplan_const_extrap_basic_.csv/|
            ^tests/regression/test_workflow/test_workflow_basic.npz/|
            ^tests/regression/test_workflow_nightly/test_workflow_nightly.npz
          )
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: local
    hooks:
      # Prevent committing .rej files from copier
      - id: forbidden-files
        name: forbidden files
        entry: found Copier update rejection files; review them and remove them
        language: fail
        files: "\\.rej$"
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.3.0'
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
      - id: ruff-format
  # additional to the above, apply black to doctests in source code
  - repo: https://github.com/keewis/blackdoc
    rev: v0.3.8
    hooks:
      - id: blackdoc
  - repo: local
    hooks:
      # pixi doesn't have a lock/check command yet,
      # so we just have to run install each time.
      # Ok for now
      - id: pixi-install
        name: pixi-install
        entry: pixi install
        # Don't use this, we want pixi to run
        # and update pixi.lock automatically if it is not up to date,
        # rather than just failing and exiting.
        # args: ["--locked"]
        language: system
        require_serial: true
        pass_filenames: false
