base_seed: 20241108
calculate_c4f10_like_monthly_fifteen_degree_pieces:
- gas: cfc114
  global_annual_mean_allyears_monthly_file: data/interim/cfc114/cfc114_global-annual-mean_allyears-monthly.nc
  latitudinal_gradient_fifteen_degree_allyears_monthly_file: data/interim/cfc114/cfc114_latitudinal-gradient_fifteen-degree_allyears-monthly.nc
  seasonality_allyears_fifteen_degree_monthly_file: data/interim/cfc114/cfc114_seasonality_fifteen-degree_allyears-monthly.nc
  step_config_id: cfc114
calculate_ch4_monthly_fifteen_degree_pieces: []
calculate_co2_monthly_fifteen_degree_pieces: []
calculate_n2o_monthly_fifteen_degree_pieces: []
calculate_sf6_like_monthly_fifteen_degree_pieces:
- allow_long_poleward_extension: true
  allow_poleward_extension: true
  gas: hfc152a
  global_annual_mean_allyears_file: data/interim/hfc152a/hfc152a_global-annual-mean_allyears.nc
  global_annual_mean_allyears_monthly_file: data/interim/hfc152a/hfc152a_global-annual-mean_allyears-monthly.nc
  lat_gradient_n_eofs_to_use: 1
  latitudinal_gradient_allyears_pcs_eofs_file: data/interim/hfc152a/hfc152a_allyears-lat-gradient-eofs-pcs.nc
  latitudinal_gradient_fifteen_degree_allyears_monthly_file: data/interim/hfc152a/hfc152a_latitudinal-gradient_fifteen-degree_allyears-monthly.nc
  latitudinal_gradient_pc0_total_emissions_regression_file: data/interim/hfc152a/hfc152a_pc0-total-emissions-regression.yaml
  observational_network_global_annual_mean_file: data/interim/hfc152a/hfc152a_observational-network_global-annual-mean.nc
  observational_network_interpolated_file: data/interim/hfc152a/hfc152a_observational-network_interpolated.nc
  observational_network_latitudinal_gradient_eofs_file: data/interim/hfc152a/hfc152a_observational-network_latitudinal-gradient-eofs.nc
  observational_network_seasonality_file: data/interim/hfc152a/hfc152a_observational-network_seasonality.nc
  pre_industrial:
    source: Guessing from reading M2017
    value:
    - 0.0
    - ppt
    year: 1985
  processed_all_data_with_bins_file: data/interim/hfc152a/hfc152a_observational-network_all-data-with-bin-information.csv
  processed_bin_averages_file: data/interim/hfc152a/hfc152a_observational-network_bin-averages.csv
  seasonality_allyears_fifteen_degree_monthly_file: data/interim/hfc152a/hfc152a_seasonality_fifteen-degree_allyears-monthly.nc
  step_config_id: hfc152a
  year_drop_observational_data_after_and_including: null
  year_drop_observational_data_before_and_including: null
ci: true
compile_historical_emissions:
- complete_historical_emissions_file: data/processed/historical_emissions
  step_config_id: only
crunch_equivalent_species: []
crunch_grids:
- fifteen_degree_monthly_file: data/interim/cfc114/cfc114_fifteen-degree_monthly.nc
  gas: cfc114
  global_mean_annual_mean_file: data/interim/cfc114/cfc114_global-mean_annual-mean.nc
  global_mean_monthly_file: data/interim/cfc114/cfc114_global-mean_monthly.nc
  hemispheric_mean_annual_mean_file: data/interim/cfc114/cfc114_hemispheric-mean_annual-mean.nc
  hemispheric_mean_monthly_file: data/interim/cfc114/cfc114_hemispheric-mean_monthly.nc
  step_config_id: cfc114
- fifteen_degree_monthly_file: data/interim/hfc152a/hfc152a_fifteen-degree_monthly.nc
  gas: hfc152a
  global_mean_annual_mean_file: data/interim/hfc152a/hfc152a_global-mean_annual-mean.nc
  global_mean_monthly_file: data/interim/hfc152a/hfc152a_global-mean_monthly.nc
  hemispheric_mean_annual_mean_file: data/interim/hfc152a/hfc152a_hemispheric-mean_annual-mean.nc
  hemispheric_mean_monthly_file: data/interim/hfc152a/hfc152a_hemispheric-mean_monthly.nc
  step_config_id: hfc152a
name: CI
plot_input_data_overviews:
- step_config_id: only
process_noaa_hats_data:
- gas: hfc152a
  processed_monthly_data_with_loc_file: data/interim/noaa/monthly_hfc152a_hats.csv
  step_config_id: hfc152a
process_noaa_in_situ_data:
- gas: ch4
  processed_monthly_data_with_loc_file: data/interim/noaa/monthly_ch4_in-situ.csv
  step_config_id: ch4
process_noaa_surface_flask_data:
- gas: ch4
  processed_monthly_data_with_loc_file: data/interim/noaa/monthly_ch4_surface-flask.csv
  step_config_id: ch4
retrieve_and_extract_agage_data:
- download_complete_file: data/raw/agage/agage/ch4_gc-md_monthly.complete
  download_urls:
  - known_hash: 6fe77860474731327b645ecf4ca0be7c280ccbb50da09ceb391c906b0c8db4da
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-md/monthly_mean/barbados/ascii/AGAGE-GCMD_RPB_ch4_mon.txt
  - known_hash: d68408ec2c8433adc5bc2d084f4cc6323996e84440bf98c00843c0c26429e3f4
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-md/monthly_mean/capegrim/ascii/AGAGE-GCMD_CGO_ch4_mon.txt
  - known_hash: d01a7d8a1bd2c277df936ce3c5ebedd5b633a70226dc4f26c32aece7e1a73b15
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-md/monthly_mean/macehead/ascii/AGAGE-GCMD_MHD_ch4_mon.txt
  - known_hash: 42f032c3766b85f0b9ff69d3c54a2e820ad27f81bca2733bb6682df8b4bf022f
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-md/monthly_mean/samoa/ascii/AGAGE-GCMD_SMO_ch4_mon.txt
  - known_hash: 1804b826f2b89e585367d3f3faa3a2ba06205b6d4248759ed4d3d8b162e54c5d
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-md/monthly_mean/trinidad/ascii/AGAGE-GCMD_THD_ch4_mon.txt
  gas: ch4
  generate_hashes: true
  instrument: gc-md
  processed_monthly_data_with_loc_file: data/interim/agage/agage/ch4_gc-md_monthly.csv
  raw_dir: data/raw/agage/agage
  step_config_id: ch4_gc-md_monthly
  time_frequency: monthly
- download_complete_file: data/raw/agage/agage/cfc114_gc-ms_monthly.complete
  download_urls:
  - known_hash: db0443235412d9f3a85d9c243f459a41adaab4eb55a3ee6c481c883ebad3541a
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-ms/monthly_mean/mtecimone/ascii/AGAGE-GCMS-MteCimone_CMN_cfc-114_mon.txt
  gas: cfc114
  generate_hashes: true
  instrument: gc-ms
  processed_monthly_data_with_loc_file: data/interim/agage/agage/cfc114_gc-ms_monthly.csv
  raw_dir: data/raw/agage/agage
  step_config_id: cfc114_gc-ms_monthly
  time_frequency: monthly
- download_complete_file: data/raw/agage/agage/cfc114_gc-ms-medusa_monthly.complete
  download_urls:
  - known_hash: ef1ce2731720ab1115b3d2de9677dd5b59136cd54a2aeda62e978c5e2e205394
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-ms-medusa/monthly_mean/barbados/ascii/AGAGE-GCMS-Medusa_RPB_cfc-114_mon.txt
  - known_hash: 187c6f9bd719b14463cdc241c38253eba4eaf83fbd5479f9ea91b64d67fff0b9
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-ms-medusa/monthly_mean/capegrim/ascii/AGAGE-GCMS-Medusa_CGO_cfc-114_mon.txt
  - known_hash: fa1a583483eefa34ce4af9ca9746237577c02731a45c3932c3d98e096e0fef70
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-ms-medusa/monthly_mean/gosan/ascii/AGAGE-GCMS-Medusa_GSN_cfc-114_mon.txt
  - known_hash: 56c37e5e98a22e10922dc6b448865b63bcecbd3fbc97b11e6d0cd71e2bf2c175
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-ms-medusa/monthly_mean/jungfraujoch/ascii/AGAGE-GCMS-Medusa_JFJ_cfc-114_mon.txt
  - known_hash: 0904a8b3fc26bebc54538118d72e07bc9a0822fcf4a007a4e27a090e45d81517
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-ms-medusa/monthly_mean/macehead/ascii/AGAGE-GCMS-Medusa_MHD_cfc-114_mon.txt
  - known_hash: ec45b9c54ac028544d1eb666bc291c97d1db4410e00c198404396a8147b4b1d7
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-ms-medusa/monthly_mean/mtecimone/ascii/AGAGE-GCMS-Medusa_CMN_cfc-114_mon.txt
  - known_hash: 4b687d3fcdbcd098ece4691eca26dfc7f6c17d8978542a43655b63a87f461610
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-ms-medusa/monthly_mean/samoa/ascii/AGAGE-GCMS-Medusa_SMO_cfc-114_mon.txt
  - known_hash: f9c1e5dbb6849dcddc536402ce864e08c5d7b60e8f1ef059812823bb43c22c7b
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-ms-medusa/monthly_mean/tacolneston/ascii/AGAGE-GCMS-Medusa_TAC_cfc-114_mon.txt
  - known_hash: e758ff12cb57f9c05c9317e108bc665769520042b02a5560ba06eae5bf0f026b
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-ms-medusa/monthly_mean/taunus/ascii/AGAGE-GCMS-Medusa_TOB_cfc-114_mon.txt
  - known_hash: bc9e6a37dd39f18252bfc5541a958af3a87b353b42a4b89adcd540fc2dc58cf0
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-ms-medusa/monthly_mean/trinidad/ascii/AGAGE-GCMS-Medusa_THD_cfc-114_mon.txt
  - known_hash: 2c6562301de71e7d1c1abb53741d9648ca1920da3f5524a38692639e7e554c70
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-ms-medusa/monthly_mean/zeppelin/ascii/AGAGE-GCMS-Medusa_ZEP_cfc-114_mon.txt
  gas: cfc114
  generate_hashes: true
  instrument: gc-ms-medusa
  processed_monthly_data_with_loc_file: data/interim/agage/agage/cfc114_gc-ms-medusa_monthly.csv
  raw_dir: data/raw/agage/agage
  step_config_id: cfc114_gc-ms-medusa_monthly
  time_frequency: monthly
- download_complete_file: data/raw/agage/agage/hfc152a_gc-ms-medusa_monthly.complete
  download_urls:
  - known_hash: c366e58f47fde3fc02e78ed474e16c438f2c395548ebd584f87551fa73c11ca6
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-ms-medusa/monthly_mean/barbados/ascii/AGAGE-GCMS-Medusa_RPB_hfc-152a_mon.txt
  - known_hash: 0bd44b35e87a256f96c50fa817e7580cadc01b84020a668d3b0fc280209a9f4c
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-ms-medusa/monthly_mean/capegrim/ascii/AGAGE-GCMS-Medusa_CGO_hfc-152a_mon.txt
  - known_hash: 9a5a0498318eb06ae57713d489aea91964437d46d610644c07c143adb6ab36a8
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-ms-medusa/monthly_mean/gosan/ascii/AGAGE-GCMS-Medusa_GSN_hfc-152a_mon.txt
  - known_hash: 47dd37a147e45f64a96b63984e54887e141b1932a0d74faceda5ee0ab87207a9
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-ms-medusa/monthly_mean/jungfraujoch/ascii/AGAGE-GCMS-Medusa_JFJ_hfc-152a_mon.txt
  - known_hash: 39000e600f6a1b0897df635248487af8132acfc94369f2120140c82ca3cb7fb3
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-ms-medusa/monthly_mean/macehead/ascii/AGAGE-GCMS-Medusa_MHD_hfc-152a_mon.txt
  - known_hash: e2c90811aab9dbb719190bebf03e5bd2a8a33ea6858846577c15de4477d9f68d
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-ms-medusa/monthly_mean/mtecimone/ascii/AGAGE-GCMS-Medusa_CMN_hfc-152a_mon.txt
  - known_hash: b8e3447b36271412591a23b057afbc5b3944b4e11d60a708689f1b2cdd5c4386
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-ms-medusa/monthly_mean/samoa/ascii/AGAGE-GCMS-Medusa_SMO_hfc-152a_mon.txt
  - known_hash: 488c4fdc902416926973469a1302e8d420dd98f2149f09728775663f2ad1fa81
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-ms-medusa/monthly_mean/tacolneston/ascii/AGAGE-GCMS-Medusa_TAC_hfc-152a_mon.txt
  - known_hash: 57f7aa8bb14ea9c646895c67032a8f3c64769e3dded3eb3ec3226e3015a77f6b
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-ms-medusa/monthly_mean/taunus/ascii/AGAGE-GCMS-Medusa_TOB_hfc-152a_mon.txt
  - known_hash: a3fc4b5cbba3ee402a0c05f93f62238d676cf4c4ab107ee104cbb293f20bd091
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-ms-medusa/monthly_mean/trinidad/ascii/AGAGE-GCMS-Medusa_THD_hfc-152a_mon.txt
  - known_hash: 6be3f7777a4fbb1398ffb4e466ce6d2c74d334b82274d1af288ddad01e6fa381
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-ms-medusa/monthly_mean/zeppelin/ascii/AGAGE-GCMS-Medusa_ZEP_hfc-152a_mon.txt
  gas: hfc152a
  generate_hashes: true
  instrument: gc-ms-medusa
  processed_monthly_data_with_loc_file: data/interim/agage/agage/hfc152a_gc-ms-medusa_monthly.csv
  raw_dir: data/raw/agage/agage
  step_config_id: hfc152a_gc-ms-medusa_monthly
  time_frequency: monthly
- download_complete_file: data/raw/agage/agage/hfc152a_gc-ms_monthly.complete
  download_urls:
  - known_hash: 8e85a45c24f9f536d3536bd405e16982809c14adff5faf04dda0563f840e7374
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-ms/monthly_mean/capegrim/ascii/AGAGE-GCMS-ADS_CGO_hfc-152a_mon.txt
  - known_hash: a2ddf728ce5fde96c8d6c1626cf694374b191664d8a3f38c65a79224e3f14959
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-ms/monthly_mean/jungfraujoch/ascii/AGAGE-GCMS-ADS_JFJ_hfc-152a_mon.txt
  - known_hash: d539619e949348c39aca9080375e1c097e1b2c3361a6bb444278c9a8dd3438ad
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-ms/monthly_mean/macehead/ascii/AGAGE-GCMS-ADS_MHD_hfc-152a_mon.txt
  - known_hash: 40c813324e9d891cb53d6dae124df63935f119dc432cc7ea4f7e9b77609b77ab
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-ms/monthly_mean/mtecimone/ascii/AGAGE-GCMS-MteCimone_CMN_hfc-152a_mon.txt
  - known_hash: 9f5014dc258a147f5365f82bcc200377b7a5b9aa692d144b5b417d66c037fc3b
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-ms/monthly_mean/zeppelin/ascii/AGAGE-GCMS-ADS_ZEP_hfc-152a_mon.txt
  gas: hfc152a
  generate_hashes: true
  instrument: gc-ms
  processed_monthly_data_with_loc_file: data/interim/agage/agage/hfc152a_gc-ms_monthly.csv
  raw_dir: data/raw/agage/agage
  step_config_id: hfc152a_gc-ms_monthly
  time_frequency: monthly
retrieve_and_extract_ale_data:
- download_complete_file: data/raw/agage/ale/ale_monthly.complete
  download_urls:
  - known_hash: 38872b27c595bfb8a1509155bd713d2f519dab5c12b51e43f9256f8fa20ca040
    url: https://agage2.eas.gatech.edu/data_archive/ale/monthly/ADR-ale.mon
  - known_hash: 7fd99c7f6014b9422da8144ff832e5b9b9ef143aa3f11ee199008d86528795b9
    url: https://agage2.eas.gatech.edu/data_archive/ale/monthly/CGO-ale.mon
  - known_hash: 1603e2401243fa73e41ac45a840c8b17a8d46cf8219aac4ac77d9824a48ce658
    url: https://agage2.eas.gatech.edu/data_archive/ale/monthly/ORG-ale.mon
  - known_hash: d6f3e73214817262950b29dd10abc260c44cc1aaf4e371b7245b804d118c7d57
    url: https://agage2.eas.gatech.edu/data_archive/ale/monthly/RPB-ale.mon
  - known_hash: f12ffc3e4f31f77e449d12f924bffa5597c5595d09a94e46f9e716398981c845
    url: https://agage2.eas.gatech.edu/data_archive/ale/monthly/SMO-ale.mon
  processed_monthly_data_with_loc_file: data/interim/agage/ale/monthly.csv
  raw_dir: data/raw/agage/ale
  step_config_id: monthly
retrieve_and_extract_gage_data:
- download_complete_file: data/raw/agage/gage/gage_monthly.complete
  download_urls:
  - known_hash: 3955484431eb728cfcbb42df2364939870f2b444367c9dab0c875052b6ff40ff
    url: https://agage2.eas.gatech.edu/data_archive/gage/monthly/CGO-gage.mon
  - known_hash: 8e7fd65035cf5b79da473d59bda2b1f499b35d211003f64a9e268cab04c59ea7
    url: https://agage2.eas.gatech.edu/data_archive/gage/monthly/MHD-gage.mon
  - known_hash: 31deafb97e07c390b5d0647f655a3dc9d82c74b918305f99505cdd6595c4ea99
    url: https://agage2.eas.gatech.edu/data_archive/gage/monthly/ORG-gage.mon
  - known_hash: b2608a3836ed41c925d7b30395fefced4e9f1706be620a607401d6f3ba578447
    url: https://agage2.eas.gatech.edu/data_archive/gage/monthly/RPB-gage.mon
  - known_hash: 5705e7d9d0f57de33ec4baaa66f9ec78d5c053f50949f1e5f60d1e8d4af5a40b
    url: https://agage2.eas.gatech.edu/data_archive/gage/monthly/SMO-gage.mon
  processed_monthly_data_with_loc_file: data/interim/agage/gage/monthly.csv
  raw_dir: data/raw/agage/gage
  step_config_id: monthly
retrieve_and_extract_noaa_data:
- download_complete_file: data/raw/noaa/ch4_in-situ.complete
  download_urls:
  - known_hash: 9eb2e865f79e6ca2fc5cd0963a52c90e0a8fd2f346b5d28d5e9989bd519d60cc
    url: https://gml.noaa.gov/aftp/data/greenhouse_gases/ch4/in-situ/surface/ch4_surface-insitu_ccgg_text.zip
  gas: ch4
  interim_files:
    monthly_data: data/interim/noaa/monthly_ch4_in-situ_raw-consolidated.csv
  raw_dir: data/raw/noaa
  source: in-situ
  step_config_id: ch4_in-situ
- download_complete_file: data/raw/noaa/ch4_surface-flask.complete
  download_urls:
  - known_hash: ea5fc01c59a67d1349ef2fdffd21ceb14ff0fb0d8518f1517d3972cac71df0e5
    url: https://gml.noaa.gov/aftp/data/trace_gases/ch4/flask/surface/ch4_surface-flask_ccgg_text.zip
  gas: ch4
  interim_files:
    events_data: data/interim/noaa/events_ch4_surface-flask_raw-consolidated.csv
    monthly_data: data/interim/noaa/monthly_ch4_surface-flask_raw-consolidated.csv
  raw_dir: data/raw/noaa
  source: surface-flask
  step_config_id: ch4_surface-flask
- download_complete_file: data/raw/noaa/hfc152a_hats.complete
  download_urls:
  - known_hash: 87101275e29241665bf53b45d4123abcc3e486a7e7d2ad879dc36744f61c4764
    url: https://gml.noaa.gov/aftp/data/hats/hfcs/hf152a_GCMS_flask.txt
  gas: hfc152a
  interim_files:
    monthly_data: data/interim/noaa/monthly_hfc152a_hats_raw-consolidated.csv
  raw_dir: data/raw/noaa
  source: hats
  step_config_id: hfc152a_hats
retrieve_and_process_epica_data:
- download_url:
    known_hash: 26c9259d69bfe390f521d1f651de8ea37ece5bbb95b43df749ba4e00f763e9fd
    url: https://doi.pangaea.de/10.1594/PANGAEA.552232?format=textfile
  processed_data_with_loc_file: data/interim/epica/epica_with_location.csv
  raw_dir: data/raw/epica
  step_config_id: only
retrieve_and_process_law_dome_data:
- doi: https://doi.org/10.25919/5bfe29ff807fb
  files_md5_sum:
    data/raw/law_dome/data/Law_Dome_GHG_2000years.xlsx: f7dd24e36565b2e213b20f90c88c990e
  processed_data_with_loc_file: data/interim/law_dome/law_dome_with_location.csv
  raw_dir: data/raw/law_dome
  step_config_id: only
retrieve_and_process_neem_data:
- download_url:
    known_hash: 3b57ca16db32f729a414422347f9292f2083c8d602f1f13d47a7fe7709d63d2d
    url: https://doi.pangaea.de/10.1594/PANGAEA.899039?format=textfile
  processed_data_with_loc_file: data/interim/neem/neem_with_location.csv
  raw_dir: data/raw/neem
  step_config_id: only
retrieve_and_process_scripps_data: []
retrieve_misc_data:
- hadcrut5:
    download_url:
      known_hash: 35ec055febd2107277e7ab965baec13ee2e0a36416e18220c8d9cbb5d509867c
      url: https://www.metoffice.gov.uk/hadobs/hadcrut5/data/HadCRUT.5.0.2.0/analysis/diagnostics/HadCRUT.5.0.2.0.analysis.summary_series.global.annual.nc
    raw_dir: data/raw/hadcrut5
  natural_earth:
    countries_shape_file_name: ne_110m_admin_0_countries.shx
    download_urls:
    - known_hash: 0f243aeac8ac6cf26f0417285b0bd33ac47f1b5bdb719fd3e0df37d03ea37110
      url: https://naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_0_countries.zip
    raw_dir: data/raw/natural_earth
  primap:
    download_url:
      known_hash: be25ecff6639638015e3a7fc7b9488de9c048bddaed1fa1a7f1d08fde12e9c04
      url: https://zenodo.org/records/10705513/files/Guetschow_et_al_2024-PRIMAP-hist_v2.5.1_final_no_rounding_27-Feb-2024.nc?download=1
    raw_dir: data/raw/primap
  step_config_id: only
smooth_law_dome_data:
- gas: ch4
  n_draws: 10
  noise_adder:
    x_ref:
    - 2024
    - yr
    x_relative_random_error:
    - 0.025
    - dimensionless
    y_random_error:
    - 3
    - ppb
  point_selector_settings:
    maximum_data_points_either_side: 10
    minimum_data_points_either_side: 4
    window_width:
    - 100
    - yr
  smoothed_draws_file: data/interim/law_dome/law-dome_ch4_smoothed_all-draws.csv
  smoothed_median_file: data/interim/law_dome/law-dome_ch4_smoothed_median.csv
  step_config_id: ch4
version: 0.2.1a1-ci
write_input4mips:
- complete_file: data/processed/esgf-ready/cfc114_input4MIPs_esgf-ready.complete
  end_year: 2022
  gas: cfc114
  input4mips_cvs_cv_source: https://raw.githubusercontent.com/znichollscr/input4MIPs_CVs/refs/heads/cr-cmip-testing/CVs/
  input4mips_cvs_source_id: CR-CMIP-testing
  input4mips_out_dir: data/processed/esgf-ready
  start_year: 1750
  step_config_id: cfc114
- complete_file: data/processed/esgf-ready/hfc152a_input4MIPs_esgf-ready.complete
  end_year: 2022
  gas: hfc152a
  input4mips_cvs_cv_source: https://raw.githubusercontent.com/znichollscr/input4MIPs_CVs/refs/heads/cr-cmip-testing/CVs/
  input4mips_cvs_source_id: CR-CMIP-testing
  input4mips_out_dir: data/processed/esgf-ready
  start_year: 1750
  step_config_id: hfc152a
