covariance:
- branch_config_id: cov
  covariance:
  - - 0.25
    - 0.5
  - - 0.5
    - 0.55
- branch_config_id: no-cov
  covariance:
  - - 0.25
    - 0.0
  - - 0.0
    - 0.55
name: dev
preparation:
- branch_config_id: only
  seed: 2847539
  seed_file: seed.txt
