name: dev
version: "0.1.0-alpha"
ci: false

retrieve_misc_data:
- step_config_id: only
  natural_earth:
    raw_dir: data/raw/natural_earth
    download_urls:
    - url: https://naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_0_countries.zip
      known_hash: 0f243aeac8ac6cf26f0417285b0bd33ac47f1b5bdb719fd3e0df37d03ea37110
    countries_shape_file_name: ne_110m_admin_0_countries.shx

# CH4, N2O and SF6 config added in `scripts/create-dev-ci-config-absolute.py`
retrieve_and_extract_noaa_data:
- step_config_id: co2_surface-flask
  gas: co2
  source: surface-flask
  download_urls:
  - url: https://gml.noaa.gov/aftp/data/trace_gases/co2/flask/surface/co2_surface-flask_ccgg_text.zip
    known_hash: 92d8a6a6c59d936f1b338c0bf781009cd25348bf9a2c8dd9dde3cbf21e8dfe17
  raw_dir: data/raw/noaa
  download_complete_file: data/raw/noaa/co2_surface-flask.complete
  interim_files:
    events_data: data/interim/noaa/events_co2_surface-flask_raw-consolidated.csv
    monthly_data: data/interim/noaa/monthly_co2_surface-flask_raw-consolidated.csv
- step_config_id: co2_in-situ
  gas: co2
  source: in-situ
  download_urls:
  - url: https://gml.noaa.gov/aftp/data/greenhouse_gases/co2/in-situ/surface/co2_surface-insitu_ccgg_text.zip
    known_hash: 0a68c9716bb9ec29e23966a2394e312618ed9b822885876d1ce5517bdf70acbe
  raw_dir: data/raw/noaa
  download_complete_file: data/raw/noaa/co2_in-situ.complete
  interim_files:
    monthly_data: data/interim/noaa/monthly_co2_in-situ_raw-consolidated.csv

process_noaa_surface_flask_data:
- step_config_id: co2
  gas: co2
  processed_monthly_data_with_loc_file: data/interim/noaa/monthly_co2_surface-flask.csv

process_noaa_in_situ_data:
- step_config_id: co2
  gas: co2
  processed_monthly_data_with_loc_file: data/interim/noaa/monthly_co2_in-situ.csv

# other gases config added in `scripts/create-dev-ci-config-absolute.py`
retrieve_and_extract_agage_data:
- step_config_id: "ccl4_gc-md_monthly"
  gas: ccl4
  instrument: gc-md
  time_frequency: monthly
  download_urls:
    - known_hash: e218c5e4f8aefb6077e55dc841733837159c2fbe8bbadad803a33b31322ac45c
      url: https://agage2.eas.gatech.edu/data_archive/agage/gc-md/monthly/barbados/ascii/AGAGE-GCMD_RPB_ccl4_mon.txt
    - known_hash: 4f54dc4c0fbaefca699d57676436358d0a46e32fda1a794cabc564bd190a32da
      url: https://agage2.eas.gatech.edu/data_archive/agage/gc-md/monthly/capegrim/ascii/AGAGE-GCMD_CGO_ccl4_mon.txt
    - known_hash: 921a67ea36d570215b3b1ca115bf4c805b4e4df593bb3dc975ce7427d62fa52d
      url: https://agage2.eas.gatech.edu/data_archive/agage/gc-md/monthly/macehead/ascii/AGAGE-GCMD_MHD_ccl4_mon.txt
    - known_hash: 33150a904cf5f1f172731eefa739625d300971a2510565e129d71f7cf50c9e8c
      url: https://agage2.eas.gatech.edu/data_archive/agage/gc-md/monthly/samoa/ascii/AGAGE-GCMD_SMO_ccl4_mon.txt
    - known_hash: 399de71b4419516f5afd3e307f67ed7751e0a13e3fa0afde4752709f819ca417
      url: https://agage2.eas.gatech.edu/data_archive/agage/gc-md/monthly/trinidad/ascii/AGAGE-GCMD_THD_ccl4_mon.txt
  raw_dir: data/raw/agage/agage
  download_complete_file: data/raw/agage/agage/ccl4_gc-md_monthly.complete
  processed_monthly_data_with_loc_file: data/interim/agage/agage/ccl4_gc-md_monthly.csv
  generate_hashes: False

retrieve_and_extract_gage_data:
- step_config_id: "monthly"
  download_urls:
    - known_hash: 3955484431eb728cfcbb42df2364939870f2b444367c9dab0c875052b6ff40ff
      url: https://agage2.eas.gatech.edu/data_archive/gage/monthly/CGO-gage.mon
    - known_hash: 8e7fd65035cf5b79da473d59bda2b1f499b35d211003f64a9e268cab04c59ea7
      url: https://agage2.eas.gatech.edu/data_archive/gage/monthly/MHD-gage.mon
    - known_hash: 31deafb97e07c390b5d0647f655a3dc9d82c74b918305f99505cdd6595c4ea99
      url: https://agage2.eas.gatech.edu/data_archive/gage/monthly/ORG-gage.mon
    - known_hash: b2608a3836ed41c925d7b30395fefced4e9f1706be620a607401d6f3ba578447
      url: https://agage2.eas.gatech.edu/data_archive/gage/monthly/RPB-gage.mon
    - known_hash: 5705e7d9d0f57de33ec4baaa66f9ec78d5c053f50949f1e5f60d1e8d4af5a40b
      url: https://agage2.eas.gatech.edu/data_archive/gage/monthly/SMO-gage.mon
  raw_dir: data/raw/agage/gage
  processed_monthly_data_with_loc_file: data/interim/agage/gage/monthly.csv
  download_complete_file: data/raw/agage/gage/gage_monthly.complete

retrieve_and_extract_ale_data:
- step_config_id: "monthly"
  download_urls:
    - known_hash: 38872b27c595bfb8a1509155bd713d2f519dab5c12b51e43f9256f8fa20ca040
      url: https://agage2.eas.gatech.edu/data_archive/ale/monthly/ADR-ale.mon
    - known_hash: 7fd99c7f6014b9422da8144ff832e5b9b9ef143aa3f11ee199008d86528795b9
      url: https://agage2.eas.gatech.edu/data_archive/ale/monthly/CGO-ale.mon
    - known_hash: 1603e2401243fa73e41ac45a840c8b17a8d46cf8219aac4ac77d9824a48ce658
      url: https://agage2.eas.gatech.edu/data_archive/ale/monthly/ORG-ale.mon
    - known_hash: d6f3e73214817262950b29dd10abc260c44cc1aaf4e371b7245b804d118c7d57
      url: https://agage2.eas.gatech.edu/data_archive/ale/monthly/RPB-ale.mon
    - known_hash: f12ffc3e4f31f77e449d12f924bffa5597c5595d09a94e46f9e716398981c845
      url: https://agage2.eas.gatech.edu/data_archive/ale/monthly/SMO-ale.mon
  raw_dir: data/raw/agage/ale
  processed_monthly_data_with_loc_file: data/interim/agage/ale/monthly.csv
  download_complete_file: data/raw/agage/ale/ale_monthly.complete

retrieve_and_process_law_dome_data:
- step_config_id: "only"
  doi: https://doi.org/10.25919/5bfe29ff807fb
  raw_dir: data/raw/law_dome
  files_md5_sum:
    data/raw/law_dome/data/Law_Dome_GHG_2000years.xlsx: f7dd24e36565b2e213b20f90c88c990e
  processed_data_with_loc_file: data/interim/law_dome/law_dome_with_location.csv

plot_input_data_overviews:
- step_config_id: only

# TODO: other gases config added in `scripts/create-dev-ci-config-absolute.py`
smooth_law_dome_data:
- step_config_id: co2
  n_draws: 10
  smoothed_draws_file: data/interim/law_dome/law-dome_co2_smoothed_all-draws.csv
  smoothed_median_file: data/interim/law_dome/law-dome_co2_smoothed_median.csv
  gas: co2
  noise_adder:
    x_ref:
    - 2024
    - yr
    x_relative_random_error:
    - 0.03  # 60 / 2000
    - dimensionless
    y_random_error:
    - 2
    - ppm
  point_selector_settings:
    window_width:
    - 120
    - yr
    minimum_data_points_either_side: 7
    maximum_data_points_either_side: 25

grid:
- step_config_id: only
  processed_data_file: data/processed/gridded/0710_fifteen-degree-gridded-data.nc

gridded_data_processing:
- step_config_id: only
  processed_data_file_global_hemispheric_means: data/processed/gridded/0810_global-hemispheric-means.nc
  processed_data_file_global_hemispheric_annual_means: data/processed/gridded/0810_global-hemispheric-annual-means.nc

write_input4mips:
- step_config_id: only
  input4mips_out_dir: data/processed/input4MIPs

quick_crunch:
- step_config_id: only
  processed_data_file_global_means: data/processed/quick_crunch/yyyy_processed-global-means.csv

analysis:
- step_config_id: only
  mean_dir: data/processed/710_means
