base_seed: 20240428
calculate_ch4_monthly_fifteen_degree_pieces:
- gas: ch4
  global_annual_mean_allyears_file: data/interim/ch4/ch4_global-annual-mean_allyears.nc
  global_annual_mean_allyears_monthly_file: data/interim/ch4/ch4_global-annual-mean_allyears-monthly.nc
  lat_gradient_n_eofs_to_use: 2
  latitudinal_gradient_allyears_pcs_eofs_file: data/interim/ch4/ch4_allyears-lat-gradient-eofs-pcs.nc
  latitudinal_gradient_fifteen_degree_allyears_monthly_file: data/interim/ch4/ch4_latitudinal-gradient_fifteen-degree_allyears-monthly.nc
  latitudinal_gradient_pc0_ch4_fossil_emissions_regression_file: data/interim/ch4/ch4_pc0-ch4-fossil-emissions-regression.yaml
  observational_network_global_annual_mean_file: data/interim/ch4/ch4_observational-network_global-annual-mean.nc
  observational_network_interpolated_file: data/interim/ch4/ch4_observational-network_interpolated.nc
  observational_network_latitudinal_gradient_eofs_file: data/interim/ch4/ch4_observational-network_latitudinal-gradient-eofs.nc
  observational_network_seasonality_file: data/interim/ch4/ch4_observational-network_seasonality.nc
  processed_bin_averages_file: data/interim/ch4/ch4_observational-network_bin-averages.csv
  seasonality_allyears_fifteen_degree_monthly_file: data/interim/ch4/ch4_seasonality_fifteen-degree_allyears-monthly.nc
  step_config_id: only
calculate_n2o_monthly_fifteen_degree_pieces:
- gas: n2o
  global_annual_mean_allyears_file: data/interim/n2o/n2o_global-annual-mean_allyears.nc
  global_annual_mean_allyears_monthly_file: data/interim/n2o/n2o_global-annual-mean_allyears-monthly.nc
  lat_gradient_n_eofs_to_use: 2
  latitudinal_gradient_allyears_pcs_eofs_file: data/interim/n2o/n2o_allyears-lat-gradient-eofs-pcs.nc
  latitudinal_gradient_fifteen_degree_allyears_monthly_file: data/interim/n2o/n2o_latitudinal-gradient_fifteen-degree_allyears-monthly.nc
  latitudinal_gradient_pc0_n2o_emissions_regression_file: data/interim/n2o/n2o_pc0-n2o-fossil-emissions-regression.yaml
  observational_network_global_annual_mean_file: data/interim/n2o/n2o_observational-network_global-annual-mean.nc
  observational_network_interpolated_file: data/interim/n2o/n2o_observational-network_interpolated.nc
  observational_network_latitudinal_gradient_eofs_file: data/interim/n2o/n2o_observational-network_latitudinal-gradient-eofs.nc
  observational_network_seasonality_file: data/interim/n2o/n2o_observational-network_seasonality.nc
  processed_bin_averages_file: data/interim/n2o/n2o_observational-network_bin-averages.csv
  seasonality_allyears_fifteen_degree_monthly_file: data/interim/n2o/n2o_seasonality_fifteen-degree_allyears-monthly.nc
  step_config_id: only
ci: false
crunch_grids:
- fifteen_degree_monthly_file: data/interim/ch4/ch4_fifteen-degree_monthly.nc
  gas: ch4
  gmnhsh_mean_annual_file: data/interim/ch4/ch4_gmnhsh-mean_annual.nc
  gmnhsh_mean_monthly_file: data/interim/ch4/ch4_gmnhsh-mean_monthly.nc
  half_degree_monthly_file: data/interim/ch4/ch4_half-degree_monthly.nc
  step_config_id: ch4
- fifteen_degree_monthly_file: data/interim/n2o/n2o_fifteen-degree_monthly.nc
  gas: n2o
  gmnhsh_mean_annual_file: data/interim/n2o/n2o_gmnhsh-mean_annual.nc
  gmnhsh_mean_monthly_file: data/interim/n2o/n2o_gmnhsh-mean_monthly.nc
  half_degree_monthly_file: data/interim/n2o/n2o_half-degree_monthly.nc
  step_config_id: n2o
name: CI
plot_input_data_overviews: []
process_noaa_in_situ_data:
- gas: ch4
  processed_monthly_data_with_loc_file: data/interim/noaa/monthly_ch4_in-situ.csv
  step_config_id: ch4
- gas: n2o
  processed_monthly_data_with_loc_file: data/interim/noaa/monthly_n2o_hats.csv
  step_config_id: n2o
process_noaa_surface_flask_data:
- gas: ch4
  processed_monthly_data_with_loc_file: data/interim/noaa/monthly_ch4_surface-flask.csv
  step_config_id: ch4
- gas: n2o
  processed_monthly_data_with_loc_file: data/interim/noaa/monthly_n2o_surface-flask.csv
  step_config_id: n2o
retrieve_and_extract_agage_data:
- download_complete_file: data/raw/agage/agage/ch4_gc-md_monthly.complete
  download_urls:
  - known_hash: e6c3955c0e9178333c5f2177088a9fe84ec27b557901364750a82241f3477300
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-md/monthly/barbados/ascii/AGAGE-GCMD_RPB_ch4_mon.txt
  - known_hash: 91cbef846e4158a880515b3b86b5b28d7510dcc6cf9494e3fec823e0c3f0678c
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-md/monthly/capegrim/ascii/AGAGE-GCMD_CGO_ch4_mon.txt
  - known_hash: 3d295bad0b883b6099ed5171044ed7a46e5ae93e8646a2020058a72c648ed0a6
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-md/monthly/macehead/ascii/AGAGE-GCMD_MHD_ch4_mon.txt
  - known_hash: e775e79fcf6cb833aa7d139c79725f25aefb81d4e90557616c4939d497f80719
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-md/monthly/samoa/ascii/AGAGE-GCMD_SMO_ch4_mon.txt
  - known_hash: fceb3a14534ce94d550f24831c7fc1258700f24b1a917005b6c06a85843ce0e1
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-md/monthly/trinidad/ascii/AGAGE-GCMD_THD_ch4_mon.txt
  gas: ch4
  generate_hashes: false
  instrument: gc-md
  processed_monthly_data_with_loc_file: data/interim/agage/agage/ch4_gc-md_monthly.csv
  raw_dir: data/raw/agage/agage
  step_config_id: ch4_gc-md_monthly
  time_frequency: monthly
- download_complete_file: data/raw/agage/agage/n2o_gc-md_monthly.complete
  download_urls:
  - known_hash: 7ac04ee39e56544dc6d98e68d52be58ab30cde620f511d70192a005c95b85fc0
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-md/monthly/barbados/ascii/AGAGE-GCMD_RPB_n2o_mon.txt
  - known_hash: 7a0d7481d6d5492bf4501c107c57c6f6b0bb9991eb9ff23abb8c9c966fefa79c
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-md/monthly/capegrim/ascii/AGAGE-GCMD_CGO_n2o_mon.txt
  - known_hash: 849efb23da2bfad5e76e5abd7303bb3b74b3bd9f924daa4303bbc10d04cf67da
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-md/monthly/macehead/ascii/AGAGE-GCMD_MHD_n2o_mon.txt
  - known_hash: 3739081cf7778e205dc1c77c74ffdb72d748baaf346858850fd39e41f16f42c3
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-md/monthly/samoa/ascii/AGAGE-GCMD_SMO_n2o_mon.txt
  - known_hash: e4cdc474f71d6f80ac63fe13b7fa61a86ce0361b7995874bf074a01c69facac3
    url: https://agage2.eas.gatech.edu/data_archive/agage/gc-md/monthly/trinidad/ascii/AGAGE-GCMD_THD_n2o_mon.txt
  gas: n2o
  generate_hashes: false
  instrument: gc-md
  processed_monthly_data_with_loc_file: data/interim/agage/agage/n2o_gc-md_monthly.csv
  raw_dir: data/raw/agage/agage
  step_config_id: n2o_gc-md_monthly
  time_frequency: monthly
retrieve_and_extract_ale_data:
- download_complete_file: data/raw/agage/ale/ale_monthly.complete
  download_urls:
  - known_hash: 38872b27c595bfb8a1509155bd713d2f519dab5c12b51e43f9256f8fa20ca040
    url: https://agage2.eas.gatech.edu/data_archive/ale/monthly/ADR-ale.mon
  - known_hash: 7fd99c7f6014b9422da8144ff832e5b9b9ef143aa3f11ee199008d86528795b9
    url: https://agage2.eas.gatech.edu/data_archive/ale/monthly/CGO-ale.mon
  - known_hash: 1603e2401243fa73e41ac45a840c8b17a8d46cf8219aac4ac77d9824a48ce658
    url: https://agage2.eas.gatech.edu/data_archive/ale/monthly/ORG-ale.mon
  - known_hash: d6f3e73214817262950b29dd10abc260c44cc1aaf4e371b7245b804d118c7d57
    url: https://agage2.eas.gatech.edu/data_archive/ale/monthly/RPB-ale.mon
  - known_hash: f12ffc3e4f31f77e449d12f924bffa5597c5595d09a94e46f9e716398981c845
    url: https://agage2.eas.gatech.edu/data_archive/ale/monthly/SMO-ale.mon
  processed_monthly_data_with_loc_file: data/interim/agage/ale/monthly.csv
  raw_dir: data/raw/agage/ale
  step_config_id: monthly
retrieve_and_extract_gage_data:
- download_complete_file: data/raw/agage/gage/gage_monthly.complete
  download_urls:
  - known_hash: 3955484431eb728cfcbb42df2364939870f2b444367c9dab0c875052b6ff40ff
    url: https://agage2.eas.gatech.edu/data_archive/gage/monthly/CGO-gage.mon
  - known_hash: 8e7fd65035cf5b79da473d59bda2b1f499b35d211003f64a9e268cab04c59ea7
    url: https://agage2.eas.gatech.edu/data_archive/gage/monthly/MHD-gage.mon
  - known_hash: 31deafb97e07c390b5d0647f655a3dc9d82c74b918305f99505cdd6595c4ea99
    url: https://agage2.eas.gatech.edu/data_archive/gage/monthly/ORG-gage.mon
  - known_hash: b2608a3836ed41c925d7b30395fefced4e9f1706be620a607401d6f3ba578447
    url: https://agage2.eas.gatech.edu/data_archive/gage/monthly/RPB-gage.mon
  - known_hash: 5705e7d9d0f57de33ec4baaa66f9ec78d5c053f50949f1e5f60d1e8d4af5a40b
    url: https://agage2.eas.gatech.edu/data_archive/gage/monthly/SMO-gage.mon
  processed_monthly_data_with_loc_file: data/interim/agage/gage/monthly.csv
  raw_dir: data/raw/agage/gage
  step_config_id: monthly
retrieve_and_extract_noaa_data:
- download_complete_file: data/raw/noaa/ch4_in-situ.complete
  download_urls:
  - known_hash: c8ad74288d860c63b6a027df4d7bf6742e772fc4e3f99a4052607a382d7fefb2
    url: https://gml.noaa.gov/aftp/data/greenhouse_gases/ch4/in-situ/surface/ch4_surface-insitu_ccgg_text.zip
  gas: ch4
  interim_files:
    monthly_data: data/interim/noaa/monthly_ch4_in-situ_raw-consolidated.csv
  raw_dir: data/raw/noaa
  source: in-situ
  step_config_id: ch4_in-situ
- download_complete_file: data/raw/noaa/ch4_surface-flask.complete
  download_urls:
  - known_hash: e541578315328857f01eb7432b5949e39beabab2017c09e46727ac49ec728087
    url: https://gml.noaa.gov/aftp/data/trace_gases/ch4/flask/surface/ch4_surface-flask_ccgg_text.zip
  gas: ch4
  interim_files:
    events_data: data/interim/noaa/events_ch4_surface-flask_raw-consolidated.csv
    monthly_data: data/interim/noaa/monthly_ch4_surface-flask_raw-consolidated.csv
  raw_dir: data/raw/noaa
  source: surface-flask
  step_config_id: ch4_surface-flask
- download_complete_file: data/raw/noaa/n2o_surface-flask.complete
  download_urls:
  - known_hash: 6b7e09c37b7fa456ab170a4c7b825b3d4b9f6eafb0ff61a2a46554b0e63e84b1
    url: https://gml.noaa.gov/aftp/data/trace_gases/n2o/flask/surface/n2o_surface-flask_ccgg_text.zip
  gas: n2o
  interim_files:
    events_data: data/interim/noaa/events_n2o_surface-flask_raw-consolidated.csv
    monthly_data: data/interim/noaa/monthly_n2o_surface-flask_raw-consolidated.csv
  raw_dir: data/raw/noaa
  source: surface-flask
  step_config_id: n2o_surface-flask
- download_complete_file: data/raw/noaa/n2o_hats.complete
  download_urls:
  - known_hash: d05fb01d87185d5020ca35a30ae40cc9c70fcc7d1e9d0640e43f09df9e568f1a
    url: https://gml.noaa.gov/aftp/data/hats/n2o/combined/GML_global_N2O.txt
  gas: n2o
  interim_files:
    monthly_data: data/interim/noaa/monthly_n2o_hats_raw-consolidated.csv
  raw_dir: data/raw/noaa
  source: hats
  step_config_id: n2o_hats
retrieve_and_process_epica_data:
- download_url:
    known_hash: 26c9259d69bfe390f521d1f651de8ea37ece5bbb95b43df749ba4e00f763e9fd
    url: https://doi.pangaea.de/10.1594/PANGAEA.552232?format=textfile
  processed_data_with_loc_file: data/interim/epica/epica_with_location.csv
  raw_dir: data/raw/epica
  step_config_id: only
retrieve_and_process_law_dome_data:
- doi: https://doi.org/10.25919/5bfe29ff807fb
  files_md5_sum:
    data/raw/law_dome/data/Law_Dome_GHG_2000years.xlsx: f7dd24e36565b2e213b20f90c88c990e
  processed_data_with_loc_file: data/interim/law_dome/law_dome_with_location.csv
  raw_dir: data/raw/law_dome
  step_config_id: only
retrieve_and_process_neem_data:
- download_url:
    known_hash: 3b57ca16db32f729a414422347f9292f2083c8d602f1f13d47a7fe7709d63d2d
    url: https://doi.pangaea.de/10.1594/PANGAEA.899039?format=textfile
  processed_data_with_loc_file: data/interim/neem/neem_with_location.csv
  raw_dir: data/raw/neem
  step_config_id: only
retrieve_and_process_scripps_data: []
retrieve_misc_data:
- natural_earth:
    countries_shape_file_name: ne_110m_admin_0_countries.shx
    download_urls:
    - known_hash: 0f243aeac8ac6cf26f0417285b0bd33ac47f1b5bdb719fd3e0df37d03ea37110
      url: https://naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_0_countries.zip
    raw_dir: data/raw/natural_earth
  primap:
    download_url:
      known_hash: 12f4097cd380cb7bb5e42ab6382fabbc5d63a478da94b5c5bb207e88c210fad8
      url: https://zenodo.org/records/10705513/files/Guetschow_et_al_2024-PRIMAP-hist_v2.5.1_final_27-Feb-2024.nc?download=1
    raw_dir: data/raw/primap
  step_config_id: only
smooth_law_dome_data:
- gas: ch4
  n_draws: 250
  noise_adder:
    x_ref:
    - 2024
    - a
    x_relative_random_error:
    - 0.025
    - dimensionless
    y_random_error:
    - 3
    - ppb
  point_selector_settings:
    maximum_data_points_either_side: 10
    minimum_data_points_either_side: 4
    window_width:
    - 100
    - a
  smoothed_draws_file: data/interim/law_dome/law-dome_ch4_smoothed_all-draws.csv
  smoothed_median_file: data/interim/law_dome/law-dome_ch4_smoothed_median.csv
  step_config_id: ch4
version: 0.1.0-dev
write_input4mips:
- complete_file: data/processed/esgf-ready/ch4_input4MIPs_esgf-ready.complete
  gas: ch4
  input4mips_out_dir: data/processed/esgf-ready
  step_config_id: ch4
- complete_file: data/processed/esgf-ready/n2o_input4MIPs_esgf-ready.complete
  gas: n2o
  input4mips_out_dir: data/processed/esgf-ready
  step_config_id: n2o
