constraint:
- branch_config_id: only
  constraint_gradient: 1.2
  draw_file: data/interim/210_constraint_draws.csv
covariance:
- branch_config_id: cov
  covariance:
  - - 0.25
    - 0.3
  - - 0.3
    - 0.55
  draw_file: data/interim/110_cov_draws.csv
- branch_config_id: cov-weak
  covariance:
  - - 0.25
    - 0.1
  - - 0.1
    - 0.55
  draw_file: data/interim/110_cov-weak_draws.csv
- branch_config_id: no-cov
  covariance:
  - - 0.25
    - 0.0
  - - 0.0
    - 0.55
  draw_file: data/interim/110_no-cov_draws.csv
covariance_plotting:
- branch_config_id: only
figures:
- branch_config_id: only
  draw_comparison_figure: figures/510_draw-comparison.pdf
  draw_comparison_table: data/processed/509_draw-table.csv
  misc_figures_dir: figures/misc
name: dev
preparation:
- branch_config_id: only
  seed: 2847539
  seed_file: data/interim/000_seed.txt
