name: dev
version: "0.1.0-alpha"
ci: false

process_noaa_data:
- step_config_id: co2_surface-flask
  gas: co2
  source: surface-flask
  download_urls:
  - url: https://gml.noaa.gov/aftp/data/trace_gases/co2/flask/surface/co2_surface-flask_ccgg_text.zip
    known_hash: 92d8a6a6c59d936f1b338c0bf781009cd25348bf9a2c8dd9dde3cbf21e8dfe17
  raw_dir: data/raw/noaa
  download_complete_file: data/raw/noaa/co2_surface-flask.complete
  processed_monthly_data_with_loc_file: data/interim/noaa/monthly_co2_surface-flask.csv
  interim_files:
    events_data: data/interim/noaa/events_co2_surface-flask_raw-consolidated.csv
    monthly_data: data/interim/noaa/monthly_co2_surface-flask_raw-consolidated.csv
retrieve:
- step_config_id: only
  natural_earth:
    raw_dir: data/raw/natural_earth
    download_urls:
    - url: https://naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_0_countries.zip
      known_hash: 0f243aeac8ac6cf26f0417285b0bd33ac47f1b5bdb719fd3e0df37d03ea37110
    countries_shape_file_name: ne_110m_admin_0_countries.shx

  # These should all be deleted/moved once we have the M17 algorithm working better
  law_dome:
    doi: https://doi.org/10.25919/5bfe29ff807fb
    raw_dir: data/raw/law_dome
    files_md5_sum:
      data/raw/law_dome/data/Law_Dome_GHG_2000years.xlsx: f7dd24e36565b2e213b20f90c88c990e
  gggrn:
    raw_dir: data/raw/gggrn
    urls_global_mean:
    - url: https://gml.noaa.gov/webdata/ccgg/trends/co2/co2_mm_gl.txt
      known_hash: 4d29a1e83b38039f0130d1bed34fd6b59b6a2c0b074cd69c39d88737b4346b27
    - url: https://gml.noaa.gov/webdata/ccgg/trends/ch4/ch4_mm_gl.txt
      known_hash: 9d28596968b777f7a5ce0e4e8737ed496aa70d9bff5fd14eb84f4d8ab2bd94ba
    - url: https://gml.noaa.gov/webdata/ccgg/trends/n2o/n2o_mm_gl.txt
      known_hash: b960224afc091028633e4f330f85a5b943018c11f470a00f1b50ae782f8cb874
process:
- step_config_id: only
  law_dome:
    processed_file: data/processed/law_dome/0101_processed-law-dome.csv
  gggrn:
    processed_file_global_mean: data/processed/gggrn/0111_processed-gggrn-global-mean.csv
grid:
- step_config_id: only
  processed_data_file: data/processed/gridded/0710_fifteen-degree-gridded-data.nc
gridded_data_processing:
- step_config_id: only
  processed_data_file_global_hemispheric_means: data/processed/gridded/0810_global-hemispheric-means.nc
  processed_data_file_global_hemispheric_annual_means: data/processed/gridded/0810_global-hemispheric-annual-means.nc
write_input4mips:
- step_config_id: only
  input4mips_out_dir: data/processed/input4MIPs
quick_crunch:
- step_config_id: only
  processed_data_file_global_means: data/processed/quick_crunch/yyyy_processed-global-means.csv
analysis:
- step_config_id: only
  mean_dir: data/processed/710_means
