name: CI

on:
  pull_request:
  push:
    branches: [main]
    tags: ['v*']

jobs:
  mypy:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          pixi-environments: "all-dev"
      - name: mypy
        run: MYPYPATH=stubs pixi run --frozen -e all-dev mypy src


  # Can add non-regression tests in here somewhere too if needed.
  # Run those even if the pull request is a draft.

  tests:
    if: ${{ !github.event.pull_request.draft }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-20.04" ]
        python-version: [ "3.11" ]
    runs-on: "${{ matrix.os }}"
    timeout-minutes: 20
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          pixi-environments: "tests"
      - name: Run tests (except nightly)
        run: |
          pixi run -e tests python scripts/write-config.py
          # Temporary fix, to be removed once we create dependencies on the fly
          pixi run -e all-dev python scripts/make-dependency-table.py --out-file-by-gas-json "data/raw/test-basic-workflow_dependencies-by-gas.json" --config-file "ci-config.yaml" --expected-number-of-writing-tasks 3 || echo "make dep json failed"
          DOIT_CONFIGURATION_FILE="ci-config.yaml" DOIT_ROOT_DIR_OUTPUT="output-bundles-tests" DOIT_RUN_ID="test-basic-workflow" pixi run -e tests doit run --verbosity=2 -n 2
          pixi run -e tests pytest -s -r a -v src tests --doctest-modules -m "not nightly"
