name: CI

on:
  pull_request:
  push:
    branches: [main]
    tags: ['v*']

jobs:
  mypy:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          pixi-environments: "all-dev"
      - name: mypy
        run: MYPYPATH=stubs pixi run --frozen -e all-dev mypy src


  # Can add non-regression tests in here somewhere too if needed.
  # Run those even if the pull request is a draft.

  tests:
    if: ${{ !github.event.pull_request.draft }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: [ "3.11" ]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          pixi-environments: "tests"
      - name: Run tests (except nightly)
        run: |
          pixi run -e tests python scripts/write-config.py
          pixi run -e tests pytest -s -r a -v src tests --doctest-modules -m "not nightly"
