name: Nightly regression tests

on:
 # # Uncomment these two lines for debugging, but leave them commented on 'main'
 # pull_request:
 #   branches: [ main ]
 # push:
 #   branches: [ main ]
 #   tags: ['v*']
 schedule:
 # 05:00 UTC = 06:00 CET = 07:00 CEST
 - cron: "0 5 * * *"
 # Manual trigger
 workflow_dispatch:

jobs:
  tests-regression:
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-20.04" ]
        python-version: [ "3.11" ]
    runs-on: "${{ matrix.os }}"
    timeout-minutes: 20
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          pixi-environments: "tests"
      - name: Run nightly tests
        run: |
          pixi run -e tests python scripts/write-config.py
          # Temporary fix, to be removed once we create dependencies on the fly
          pixi run -e all-dev python scripts/make-dependency-table.py --out-file-by-gas-json "data/raw/test-nightly-workflow_dependencies-by-gas.json" --config-file "ci-nightly-config.yaml" --expected-number-of-writing-tasks 8 || echo "make dep json failed"
          DOIT_CONFIGURATION_FILE="ci-nightly-config.yaml" DOIT_ROOT_DIR_OUTPUT="output-bundles-tests" DOIT_RUN_ID="test-nightly-workflow" pixi run -e tests doit run --verbosity=2 -n 2
          pixi run -e tests pytest -s -r a -v src tests --doctest-modules -m nightly
