name: Nightly regression tests

on:
 # # Uncomment these two lines for debugging, but leave them commented on 'main'
 # pull_request:
 #   branches: [ main ]
 # push:
 #   branches: [ main ]
 #   tags: ['v*']
 schedule:
 # 05:00 UTC = 06:00 CET = 07:00 CEST
 - cron: "0 5 * * *"

jobs:
  tests-regression:
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-20.04" ]
        python-version: [ "3.11" ]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          pixi-environments: "tests"
      - name: Run nightly tests
        run: |
          pixi run -e tests python scripts/write-config.py
          DOIT_CONFIGURATION_FILE="ci-nightly-config.yaml" DOIT_ROOT_DIR_OUTPUT="output-bundles-tests" DOIT_RUN_ID="test-nightly-workflow" pixi run -e tests doit run --verbosity=2 -n 2
          pixi run -e tests pytest -s -r a -v src tests --doctest-modules -m nightly
