name: Nightly regression tests

on:
 # Uncomment these two lines for debugging, but leave them commented on 'main'
 pull_request:
   branches: [ main ]
 push:
   branches: [ main ]
   tags: ['v*']
 schedule:
 # 05:00 UTC = 06:00 CET = 07:00 CEST
 - cron: "0 5 * * *"

jobs:
  tests-regression:
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-20.04" ]
        python-version: [ "3.11" ]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          pixi-environments: "tests"
      - name: Run tests relevant for coverage
        run: |
          pixi run -e tests python scripts/write-config.py
          DOIT_CONFIGURATION_FILE="ci-nightly-config.yaml" DOIT_ROOT_DIR_OUTPUT="output-bundles-tests" DOIT_RUN_ID="test-nightly-workflow" pixi run -e tests doit run --verbosity=2 -n 2
          pixi run -e tests pytest -s -r a -v src tests --doctest-modules -m "not coverage_breaker" --cov=src --cov-report=term-missing --cov-report=xml
          pixi run -e tests coverage report
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Run tests that break coverage
        run: |
          pixi run -e tests pytest -s -r a -v tests -m coverage_breaker
